USE [master]
GO

/****** Object:  Database [VacationPlanner]    Script Date: 29.10.2022 10:56:05 ******/
CREATE DATABASE [VacationPlanner]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VacationPlaner', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\VacationPlaner.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VacationPlaner_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\VacationPlaner_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VacationPlanner].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VacationPlanner] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VacationPlanner] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VacationPlanner] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VacationPlanner] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VacationPlanner] SET ARITHABORT OFF 
GO

ALTER DATABASE [VacationPlanner] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VacationPlanner] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VacationPlanner] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VacationPlanner] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VacationPlanner] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VacationPlanner] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VacationPlanner] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VacationPlanner] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VacationPlanner] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VacationPlanner] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VacationPlanner] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VacationPlanner] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VacationPlanner] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VacationPlanner] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VacationPlanner] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VacationPlanner] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VacationPlanner] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VacationPlanner] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VacationPlanner] SET  MULTI_USER 
GO

ALTER DATABASE [VacationPlanner] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VacationPlanner] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VacationPlanner] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VacationPlanner] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VacationPlanner] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VacationPlanner] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [VacationPlanner] SET QUERY_STORE = OFF
GO

ALTER DATABASE [VacationPlanner] SET  READ_WRITE 
GO

